name: Release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.ref_name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          gh release create "$RELEASE_TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$RELEASE_TAG" \
            --generate-notes
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - arm64
          - amd64
          - arm
        os:
          - linux
    env:
      GOARCH: ${{ matrix.architecture }}
      GOOS: ${{ matrix.os }}
      RELEASE_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.0'
      - name: Install dependencies
        run: go get .
      - name: Compile
        run: go build -o gocacert-${{ matrix.os }}-${{ matrix.architecture }} -v .
      - name: Upload to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$RELEASE_TAG" \
            --repo="$GITHUB_REPOSITORY" \
            gocacert-${{ matrix.os }}-${{ matrix.architecture }}
